services:
  database:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-joomladb}
      POSTGRES_USER: ${POSTGRES_USER:-joomlauser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-joomlapassword}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-joomlauser} -d ${POSTGRES_DB:-joomladb}"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - backend_net

  joomla:
    image: joomla:latest
    container_name: joomla_app
    restart: always
    environment:
      JOOMLA_DB_HOST: database
      JOOMLA_DB_TYPE: pgsql
      JOOMLA_DB_USER: ${POSTGRES_USER:-joomlauser}
      JOOMLA_DB_PASSWORD: ${POSTGRES_PASSWORD:-joomlapassword}
      JOOMLA_DB_NAME: ${POSTGRES_DB:-joomladb}

      JOOMLA_SITE_NAME: ${JOOMLA_SITE_NAME:-Sitio Institucional UMNG}
      JOOMLA_ADMIN_USER: ${JOOMLA_ADMIN_USER:-Administrador UMNG}
      JOOMLA_ADMIN_USERNAME: ${JOOMLA_ADMIN_USERNAME:-admin}
      JOOMLA_ADMIN_PASSWORD: ${JOOMLA_ADMIN_PASSWORD:-AdminUMNG2026!!}
      JOOMLA_ADMIN_EMAIL: ${JOOMLA_ADMIN_EMAIL:-admin@localhost.com}

    volumes:
      - joomla_data:/var/www/html

    depends_on:
      database:
        condition: service_healthy

    networks:
      - frontend_net
      - backend_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana_app
    restart: always
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD:-admin}
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_ANONYMOUS_ORG_NAME=Main Org.
      - GF_SERVER_ROOT_URL=http://localhost/grafana/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    networks:
      - frontend_net
      - backend_net

  jupyter:
    image: jupyter/scipy-notebook:latest
    container_name: jupyter_notebook
    restart: always
    command: start-notebook.sh --ServerApp.token='' --ServerApp.password='' --ServerApp.base_url='/jupyter/' --ServerApp.disable_check_xsrf=True
    volumes:
      - ./jupyter/notebooks:/home/jovyan/work
    networks:
      - frontend_net
      - backend_net

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - joomla
      - grafana
      - jupyter
    networks:
      - frontend_net

volumes:
  pg_data:
  grafana_data:
  joomla_data:

networks:
  frontend_net:
    driver: bridge
  backend_net:
    driver: bridge