apiVersion: 1

datasources:
  - name: PostgreSQL
    type: postgres
    access: proxy
    url: database:5432
    user: joomlauser
    secureJsonData:
      password: "joomlapassword"
    jsonData:
      database: joomladb
      sslmode: "disable"
      postgresVersion: 1600
    isDefault: true
    editable: false